"use client";

import { useMemo, useState, type ReactNode } from "react";
import { AutomationDetails, type AutomationView } from "./automation-center";
import type { Candle, Props } from "./automation-mobile";
import { buildPremiumAssets, type PremiumAsset, type PremiumSlot } from "./premium-model";
import { PremiumControls } from "./premium-controls";
import { AssetIcon, PremiumBrand, PremiumDrawer, PremiumIcon, displayMoney as money, displayNumber as number, displayTime as time, type IconName } from "./premium-primitives";
import "./premium-automation.css";

type Presentation = Props & { athProfiles?: Array<{ environment: string; asset: string; regime: string }>; deploymentSha?: string };
type Panel = "strategy" | "simulator" | "adjustments" | "config" | "asset" | "slot" | "audit" | "menu" | null;
const labels = { overview: "Visão Geral", shadow: "Shadow", testnet: "Testnet", live: "Real" };
const tones = (value: number | null) => value == null ? "" : value < 0 ? "px-negative" : "px-positive";
const protectedSlot = (slot: PremiumSlot, model: PremiumAsset) => slot.orders.some((order) => order.side === "SELL" && (order.resident || model.environment === "SHADOW" && order.status === "VIRTUAL_TP"));
const total = (assets: PremiumAsset[], key: "committed" | "exposure" | "realizedPnl" | "openPnl" | "capital" | "freeCapital") => assets.every((asset) => asset[key] !== null) ? assets.reduce((sum, asset) => sum + (asset[key] ?? 0), 0) : null;

function Trend({ candles, asset, symbol, large = false }: { candles: Candle[]; asset: string; symbol: string; large?: boolean }) {
  const values = candles.map((row) => Number(row.close_price)).filter(Number.isFinite);
  if (values.length < 2) return <div className="px-trend-empty">Histórico {symbol} indisponível</div>;
  const min = Math.min(...values), range = Math.max(...values) - min || 1;
  const points = values.map((value, index) => `${(index * 600 / (values.length - 1)).toFixed(1)},${(76 - (value - min) / range * 64).toFixed(1)}`).join(" ");
  return <svg className={`px-trend ${large ? "px-trend--large" : ""} px-${asset.toLowerCase()}`} viewBox="0 0 600 84" preserveAspectRatio="none" role="img" aria-label={`Histórico diário ${symbol}, ${values.length} velas públicas Binance`}><defs><linearGradient id={`trend-${symbol}-${large}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".25" /><stop offset="100%" stopColor="currentColor" stopOpacity="0" /></linearGradient></defs><path d={`M0,84 L${points.replaceAll(" ", " L")} L600,84 Z`} fill={`url(#trend-${symbol}-${large})`} /><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.2" vectorEffect="non-scaling-stroke" strokeLinejoin="round" /></svg>;
}
function Metric({ label, value, note, icon, tone = "", percent }: { label: string; value: string; note?: string; icon: IconName; tone?: string; percent?: number | null }) {
  return <article className="px-metric"><span>{label}</span><strong className={tone}>{value}</strong>{percent != null ? <div className="px-meter"><i style={{ width: `${Math.min(100, Math.max(0, percent))}%` }} /></div> : <PremiumIcon name={icon} className={tone} />}{note ? <small>{note}</small> : null}</article>;
}
function AssetCard({ model, candles, regime, onOpen }: { model: PremiumAsset; candles: Candle[]; regime?: string; onOpen: () => void }) {
  const open = model.slots.filter((slot) => slot.state === "OPEN" || slot.state === "TP_ACTIVE" || slot.label === "ABERTO");
  const quantity = open.reduce((sum, slot) => sum + (slot.quantity ?? 0), 0);
  const tp = model.orders.filter((order) => order.side === "SELL" && (order.resident || model.environment === "SHADOW" && order.status === "VIRTUAL_TP"));
  const next = model.slots.find((slot) => slot.state === "NEXT_BUY");
  const last = candles.at(-1), previous = candles.at(-2);
  const change = last && previous ? (Number(last.close_price) / Number(previous.close_price) - 1) * 100 : null;
  return <article className={`px-asset px-panel px-${model.asset.toLowerCase()}`}>
    <header><AssetIcon asset={model.asset} /><div><h2>{model.symbol.replace(model.currency, `/${model.currency}`)}</h2><strong className="px-price">{number(model.price)}</strong></div><div className="px-asset-status"><span className={`px-badge ${model.health.tone === "error" ? "px-badge--error" : ""}`}>{regime ?? model.regime ?? model.status}</span>{change !== null ? <small className={tones(change)}>{change >= 0 ? "↗ +" : "↘ "}{number(change)}% <span>vela diária</span></small> : null}</div></header>
    <Trend candles={candles} asset={model.asset} symbol={`${model.asset}${model.environment === "REAL" ? "BRL" : "USDC"}`} />
    {model.environment === "TESTNET" ? <small className="px-chart-source">Curva Production de referência · execução fictícia Testnet</small> : null}
    <div className="px-asset-facts"><div><span>Posição CoinOps</span><strong>{number(quantity, 8)}</strong><small>{money(model.committed, model.currency)}</small></div><div><span>Gains</span><strong>{model.gains ?? "—"}</strong><small>{model.goal}/slot/mês</small></div><div><span>{model.environment === "SHADOW" ? "TP virtual" : "TP residente"}</span><strong>{tp.length ? number(tp[0].price, model.asset === "BTC" ? 0 : 2) : "—"}</strong><small>{model.tpCount} proteção(ões)</small></div><div><span>Próx. BUY</span><strong>{number(next?.entryPrice, model.asset === "BTC" ? 0 : 2)}</strong><small>{next ? `Slot #${next.number}` : "Sem entrada armada"}</small></div></div>
    <button type="button" className="px-asset-button" onClick={onOpen}>Ver {model.asset}<PremiumIcon name="arrow" /></button>
  </article>;
}
function SlotList({ model, onSelect }: { model: PremiumAsset; onSelect: (slot: PremiumSlot) => void }) {
  const [filter, setFilter] = useState("operational");
  const [all, setAll] = useState(false);
  const rows = [...model.slots].filter((slot) => filter === "reached" ? slot.targetReached : filter === "eligible" ? slot.eligible : filter === "open" ? slot.state === "OPEN" : filter === "waiting" ? slot.state !== "OPEN" && slot.state !== "NEXT_BUY" && !slot.targetReached : true)
    .sort((a, b) => filter === "physical" ? a.number - b.number : filter === "gain_desc" ? (b.gains ?? 0) - (a.gains ?? 0) : filter === "gain_asc" ? (a.gains ?? 0) - (b.gains ?? 0) : (a.rank ?? 99) - (b.rank ?? 99) || a.number - b.number);
  return <section className="px-slot-section"><div className="px-section-heading"><h3>Slots {model.asset} <small>{model.slots.length} físicos</small></h3><label className="px-select-label">Ordenação<select aria-label="Ordenação dos slots" value={filter} onChange={(event) => setFilter(event.target.value)}>{[["operational", "Ordem operacional"], ["physical", "Slot físico"], ["gain_desc", "Mais gains"], ["gain_asc", "Menos gains"], ["reached", "Meta batida"], ["eligible", "Elegíveis"], ["open", "OPEN"], ["waiting", "Aguardando"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <div className="px-slot-summary">{[["OPEN", model.openCount], ["TP", model.tpCount], ["NEXT BUY", model.nextCount], ["PLANNED", model.plannedCount], ["META BATIDA", model.slots.filter((slot) => slot.targetReached).length], ["GAINS", model.gains]].map(([label, value]) => <span key={label}><strong>{value ?? "—"}</strong>{label}</span>)}</div>
    <div className="px-table-wrap"><table className="px-table px-slot-table"><thead><tr><th>Slot / rank</th><th>Status</th><th>Entrada / atual</th><th>TP</th><th>P&L aberto</th><th>Gains mês</th><th>Próxima ação</th></tr></thead><tbody>{(all ? rows : rows.slice(0, 6)).map((slot) => <tr key={slot.number} data-testid="premium-slot-row"><td><strong>#{slot.number}</strong><small>Rank {slot.rank ?? "—"}</small></td><td><span className={`px-badge px-state-${slot.state.toLowerCase()}`}>{slot.label}</span>{slot.targetReached ? <small className="px-warning">META BATIDA</small> : null}</td><td data-label="Entrada / atual">{number(slot.entryPrice)}<small>{number(slot.currentPrice)}</small></td><td data-label="TP">{number(slot.tpPrice)}</td><td data-label="P&L" className={tones(slot.openPnl)}>{number(slot.openPnl, 4)}</td><td data-label="Mês / meta">{slot.monthlyGains ?? "?"}/{slot.goal}<small>{slot.gains ?? "—"} totais</small></td><td><button type="button" className="px-row-link" onClick={() => onSelect(slot)} aria-label={`Detalhes do slot ${slot.number}`}>{slot.nextAction}<span aria-hidden="true">›</span></button></td></tr>)}</tbody></table></div>
    {rows.length > 6 ? <button type="button" className="px-text-button" onClick={() => setAll(!all)}>{all ? "Recolher lista" : `Ver todos os ${rows.length} slots`}</button> : null}
    <p className="px-caption">Rank é operacional; o slot físico nunca muda. Meta mensal por slot · lifetime preservado.</p>
  </section>;
}

export function PremiumAutomation({ view, data, userLabel, strategyPanel, adjustmentsPanel, marketTicker, initialAdjustments = false }: { view: AutomationView; data: Presentation; userLabel: string; strategyPanel: ReactNode; adjustmentsPanel: ReactNode; marketTicker?: ReactNode; initialAdjustments?: boolean }) {
  const [panel, setPanel] = useState<Panel>(initialAdjustments ? "adjustments" : null);
  const [asset, setAsset] = useState<"BTC" | "SOL">("BTC");
  const [selectedSlot, setSelectedSlot] = useState<PremiumSlot | null>(null);
  const [operationTab, setOperationTab] = useState("positions");
  const [historyLimit, setHistoryLimit] = useState(8);
  const environment = view === "shadow" ? "SHADOW" : view === "testnet" ? "TESTNET" : "REAL";
  const assets = useMemo(() => buildPremiumAssets(data, environment), [data, environment]);
  const overview = useMemo(() => view === "overview" ? (["SHADOW", "TESTNET", "REAL"] as const).map((env) => ({ env, assets: buildPremiumAssets(data, env) })) : [], [data, view]);
  const active = assets.find((item) => item.asset === asset)!;
  const currency = environment === "REAL" ? "BRL" : "USDC";
  const health = data.livePreparation?.executor.health;
  const liveActive = Object.values(data.liveAssetData ?? {}).some((entry) => entry.run.status === "ACTIVE");
  const globalOverCap = environment === "REAL" && data.livePreparation && (total(assets, "exposure") ?? 0) > data.livePreparation.globalCapBrl;
  const healthy = assets.every((item) => item.health.healthy) && !globalOverCap;
  const checked = assets.map((item) => item.lastCheck).filter((value): value is string => !!value).sort()[0];
  const cap = environment === "REAL" ? data.livePreparation?.globalCapBrl ?? null : total(assets, "capital");
  const exposure = total(assets, "exposure");
  const percent = cap && exposure !== null ? exposure / cap * 100 : null;
  const events = assets.flatMap((item) => item.events.map((event) => ({ ...event, asset: item.asset }))).sort((a, b) => (b.at ?? "").localeCompare(a.at ?? ""));
  const positions = assets.flatMap((item) => item.slots.filter((slot) => slot.state === "OPEN").map((slot) => ({ model: item, slot })));
  const orders = assets.flatMap((item) => item.orders.map((order) => ({ ...order, asset: item.asset })));
  const alerts = assets.flatMap((item) => item.alerts.map((alert) => ({ asset: item.asset, alert })));
  const openAsset = (next: "BTC" | "SOL") => { setAsset(next); setPanel("asset"); };
  const openSlot = (slot: PremiumSlot, next = asset) => { setAsset(next); setSelectedSlot(slot); setPanel("slot"); };
  const candlesFor = (item: PremiumAsset) => data.dailyCandles.filter((row) => row.symbol === `${item.asset}${item.currency}`).sort((a, b) => a.candle_open_at.localeCompare(b.candle_open_at));
  const goOperations = () => document.getElementById("premium-operations")?.scrollIntoView({ behavior: "smooth", block: "start" });
  const title = panel === "slot" ? `${asset} · Slot físico #${selectedSlot?.number}` : panel === "asset" ? `${asset}/${currency} · operações e slots` : panel === "strategy" ? "Estratégia e regime ATH" : panel === "adjustments" ? "Ajustes manuais" : panel === "config" ? "Configurações e controles" : panel === "simulator" ? "Simuladores isolados" : panel === "audit" ? "Análise e auditoria completa" : "Navegação CoinOps";
  return <div className="px-app" data-testid="premium-automation" data-environment={environment}>
    <header className="px-topbar"><PremiumBrand /><div className="px-top-status"><span className={`px-live ${liveActive ? "is-live" : ""}`}><i />{liveActive ? "LIVE" : "EM PREPARAÇÃO"}</span><small>Executor {data.livePreparation?.executor.ip ?? "não consultado"}<br />Binance Production</small></div><button className="px-avatar" type="button" aria-label="Abrir menu" onClick={() => setPanel("menu")}>{userLabel.slice(0, 2).toUpperCase()}</button><button className="px-mobile-menu px-icon-button" type="button" aria-label="Abrir menu" onClick={() => setPanel("menu")}><PremiumIcon name="menu" /></button></header>
    <nav className="px-environments" aria-label="Ambientes da Automação">{(Object.keys(labels) as AutomationView[]).map((item) => <a key={item} href={`/automacao?view=${item}`} aria-current={view === item ? "page" : undefined}>{labels[item]}{item === "live" && liveActive ? <i /> : null}</a>)}<span>Central operacional</span></nav>
    <nav className="px-toolbar" aria-label="Ferramentas da Automação" data-testid="premium-toolbar">{([
      ["home", "Início", () => window.scrollTo({ top: 0, behavior: "smooth" })], ["orders", "Operações", goOperations], ["strategy", "Estratégia", () => setPanel("strategy")], ["simulator", "Simulador", () => setPanel("simulator")], ["adjust", "Ajustes", () => setPanel("adjustments")], ["reports", "Relatórios", null], ["settings", "Configurações", () => setPanel("config")],
    ] as Array<[IconName, string, (() => void) | null]>).map(([icon, label, action]) => action ? <button key={label} type="button" onClick={action} className={icon === "home" ? "is-active" : ""}><PremiumIcon name={icon} />{label}</button> : <a key={label} href="/relatorios"><PremiumIcon name={icon} />{label}</a>)}</nav>
    <main className="px-dashboard">
      <section className="px-hero px-panel"><div className="px-greeting"><span className="px-eyebrow">{labels[view]} · {environment === "REAL" ? "BINANCE SPOT" : environment === "TESTNET" ? "FUNDOS FICTÍCIOS" : "SIMULAÇÃO VIRTUAL"}</span><h1>Olá, {userLabel.split("@")[0].split(/[ ._-]/)[0]}!</h1><p>{view === "overview" ? "Toda a operação, em uma única visão." : healthy ? environment === "REAL" ? "Seu robô está operando no servidor." : "Acompanhe sua estratégia em tempo real." : "Acompanhe o estado e os avisos da operação."}</p></div><div className={`px-health ${healthy ? "" : "px-health--attention"}`}><div><h2>Sistema Operacional</h2><p><i>{environment === "REAL" ? health?.healthy ? "✓" : "!" : healthy ? "✓" : "!"}</i>{environment === "REAL" ? "Executor" : "Motor"} <strong>{environment === "REAL" ? health?.healthy ? "ONLINE" : "VERIFICAR" : healthy ? "ATIVO" : "ATENÇÃO"}</strong></p><p><i>{environment === "REAL" ? health?.binance_connectivity === "OK" ? "✓" : "!" : "·"}</i>{environment === "REAL" ? "Binance" : environment} <strong>{environment === "REAL" ? health?.binance_connectivity === "OK" ? "CONNECTED" : "VERIFICAR" : "ISOLADO"}</strong></p><p><i>{healthy ? "✓" : "!"}</i>Estratégia <strong>{healthy ? "ATIVA" : "VERIFICAR"}</strong></p></div><div className="px-health-check"><small>Última verificação<br /><time>{time(checked)}</time></small><button type="button" className="px-button" onClick={() => { setOperationTab("alerts"); goOperations(); }}>Ver logs <PremiumIcon name="arrow" /></button></div></div></section>
      {!healthy ? <div className="px-alert-banner" role="status">{globalOverCap ? <p><strong>LIMITE GLOBAL EXCEDIDO</strong>Verifique a reconciliação e os limites autorizados.</p> : null}{assets.filter((item) => !item.health.healthy).map((item) => <p key={item.asset}><strong>{item.asset} · {item.health.label}</strong> {item.health.reason}</p>)}</div> : null}
      {view === "overview" ? <section className="px-overview-grid" aria-label="Resumo dos três ambientes">{overview.map(({ env, assets: group }) => <a className={`px-panel px-overview-card px-env-${env.toLowerCase()}`} key={env} href={`/automacao?view=${env === "REAL" ? "live" : env.toLowerCase()}`}><header><h2>{env === "REAL" ? "Real · LIVE" : env === "SHADOW" ? "Shadow" : "Testnet"}</h2><span className={`px-badge ${group.some((item) => !item.health.healthy) ? "px-badge--warning" : ""}`}>{group.every((item) => item.health.healthy) ? "OPERACIONAL" : "ACOMPANHAR"}</span></header><strong>{money(total(group, "capital"), env === "REAL" ? "BRL" : "USDC")}</strong><small>{env === "REAL" ? "Capital lógico autorizado" : "Capital lógico · sem dinheiro real"}</small><div>{group.map((item) => <span key={item.asset}><AssetIcon asset={item.asset} /><b>{item.asset}</b>{item.openCount} OPEN · {item.gains ?? "—"} gains<PremiumIcon name="arrow" /></span>)}</div></a>)}</section> : null}
      <section className="px-kpis" aria-label={`Indicadores ${labels[view]}`}>
        <Metric label={environment === "REAL" ? "Saldo BRL livre · Binance" : "Capital lógico livre"} value={money(environment === "REAL" ? data.livePreparation?.brlFree : total(assets, "freeCapital"), currency)} note={environment === "REAL" ? "Saldo da conta ≠ limite CoinOps" : "Virtual · sem saldo real"} icon="wallet" />
        <Metric label="Capital em posições" value={money(total(assets, "committed"), currency)} note={`${positions.length} posições próprias`} icon="orders" />
        <Metric label="P&L realizado · acumulado" value={money(total(assets, "realizedPnl"), currency)} note={`Aberto ${money(total(assets, "openPnl"), currency)}`} icon="chart" tone={tones(total(assets, "realizedPnl"))} />
        <Metric label="Exposição total" value={money(exposure, currency)} note="Posições + reservas de BUY" icon="shield" />
        <Metric label={environment === "REAL" ? "Limite global CoinOps" : "Capital lógico total"} value={money(cap, currency)} note={percent !== null ? `${number(percent, 1)}% comprometido` : "Sem evidência disponível"} icon="wallet" percent={percent} />
      </section>
      <section className="px-assets" aria-label={`Ativos ${labels[view]}`}>{assets.map((model) => <AssetCard key={model.asset} model={model} candles={candlesFor(model)} regime={data.athProfiles?.find((profile) => profile.asset === model.asset && profile.environment === environment)?.regime} onOpen={() => openAsset(model.asset)} />)}</section>
      <section className="px-operations px-panel" id="premium-operations"><div className="px-operations-nav" data-testid="premium-operations-tabs" role="tablist" aria-label="Operações" onKeyDown={(event) => { const tabs = Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')); const index = tabs.indexOf(document.activeElement as HTMLButtonElement); const next = event.key === "ArrowRight" ? (index + 1) % tabs.length : event.key === "ArrowLeft" ? (index - 1 + tabs.length) % tabs.length : event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : null; if (next !== null) { event.preventDefault(); tabs[next]?.focus(); tabs[next]?.click(); } }}>{[["positions", `Posições abertas (${positions.length})`], ["next", `Próximas BUYs (${assets.reduce((sum, item) => sum + item.nextCount, 0)})`], ["history", "Histórico de operações"], ["alerts", `Alertas (${Math.max(alerts.length, assets.reduce((sum, item) => sum + item.activeIssueCount, 0))})`]].map(([key, label]) => <button type="button" role="tab" id={`px-tab-${key}`} aria-controls="px-operations-content" tabIndex={operationTab === key ? 0 : -1} aria-selected={operationTab === key} key={key} onClick={() => setOperationTab(key)}>{label}</button>)}<button type="button" className="px-button px-all-operations" onClick={() => setPanel("asset")}>Todos os slots <PremiumIcon name="arrow" /></button></div>
        <div role="tabpanel" id="px-operations-content" aria-labelledby={`px-tab-${operationTab}`}>
        {operationTab === "positions" ? <div className="px-table-wrap"><table className="px-table px-position-table"><thead><tr><th>Ativo / slot</th><th>Tipo</th><th>Quantidade</th><th>Entrada / atual</th><th>TP</th><th>P&L aberto</th><th>Status</th><th /></tr></thead><tbody>{positions.map(({ model, slot }) => <tr key={`${model.asset}-${slot.number}`}><td><AssetIcon asset={model.asset} /><strong>{model.asset}</strong><small>#{slot.number}</small></td><td>BUY · posição</td><td data-label="Quantidade">{number(slot.quantity, 8)}</td><td data-label="Entrada / atual">{number(slot.entryPrice)}<small>{number(model.price)}</small></td><td data-label="TP">{number(slot.tpPrice)}</td><td data-label="P&L" className={tones(slot.openPnl)}>{number(slot.openPnl, 4)}</td><td><span className={`px-badge ${protectedSlot(slot, model) ? "" : "px-badge--error"}`}>{protectedSlot(slot, model) ? model.environment === "SHADOW" ? "TP VIRTUAL" : "TP ATIVO" : "SEM TP"}</span></td><td><button type="button" aria-label={`Ver posição ${model.asset} slot ${slot.number}`} onClick={() => openSlot(slot, model.asset)}>Ver ›</button></td></tr>)}</tbody></table>{!positions.length ? <p className="px-empty">Nenhuma posição aberta neste ambiente.</p> : null}</div> : null}
        {operationTab === "next" ? <div className="px-next-list">{assets.map((model) => <div key={model.asset}><h3><AssetIcon asset={model.asset} />{model.asset}/{model.currency}</h3>{model.orders.filter((order) => order.side === "BUY" && ["NEW", "PARTIALLY_FILLED", "PREPARED", ...(environment === "SHADOW" ? ["ARMED"] : [])].includes(order.status)).map((order) => <p key={order.id}><span>Slot #{order.slotNumber} · {money(order.price, currency)}</span><span className="px-badge px-badge--warning">{order.resident ? "RESIDENTE NA BINANCE" : environment === "SHADOW" ? "VIRTUAL · ARMADA" : "PREPARADA · NÃO RESIDENTE"}</span></p>)}<button type="button" className="px-text-button" onClick={() => openAsset(model.asset)}>{model.plannedCount} níveis planejados no CoinOps · ver fila →</button></div>)}</div> : null}
        {operationTab === "history" ? <div className="px-history"><p className="px-caption">Ordens do ciclo carregado. Valores e taxas adicionais estão na análise completa e nos relatórios.</p>{orders.filter((order) => ["FILLED", "CANCELED", "CANCELLED", "REJECTED", "EXPIRED"].includes(order.status)).slice(-historyLimit).reverse().map((order) => <div className="px-history-row" key={order.id}><AssetIcon asset={order.asset} /><strong>{order.asset} #{order.slotNumber}</strong><span className={order.side === "BUY" ? "px-info" : "px-negative"}>{order.side} · {order.purpose}</span><span>{number(order.executedQuantity, 8)}<small>{money(order.quote, currency)}</small></span><span className="px-badge">{order.status}</span><small>{time(order.at)}</small></div>)}<button type="button" className="px-text-button" onClick={() => setHistoryLimit(historyLimit + 12)}>Mostrar mais histórico</button><button type="button" className="px-text-button" onClick={() => setPanel("audit")}>Análise completa de ganhos, fees e ciclos →</button></div> : null}
        {operationTab === "alerts" ? <div className="px-alert-list">{assets.map((model) => <div key={model.asset}><h3>{model.asset} · {model.health.label}</h3><p>{model.health.reason}</p>{model.alerts.map((alert, index) => <pre className="px-alert-detail" key={index}>{JSON.stringify(alert, null, 2)}</pre>)}<small>{model.historicalCount} ocorrências históricas preservadas · {model.activeIssueCount} ativas</small></div>)}<button type="button" className="px-text-button" onClick={() => setPanel("audit")}>Ver eventos e auditoria detalhada →</button></div> : null}
        </div>
      </section>
      <div className="px-lower-grid"><section className="px-panel px-capital"><h2>Distribuição do capital</h2><div className="px-capital-body"><div className="px-donut" style={{ background: `conic-gradient(#ffac26 0 ${cap ? (assets[0].committed ?? 0) / cap * 100 : 0}%, #6588ff 0 ${cap ? (total(assets, "committed") ?? 0) / cap * 100 : 0}%, #23374b 0 100%)` }}><div><strong>{money(total(assets, "committed"), currency)}</strong><small>em posições</small></div></div><dl>{assets.map((item) => <div key={item.asset}><dt><i className={`px-dot-${item.asset.toLowerCase()}`} />{item.asset}</dt><dd>{money(item.committed, currency)}</dd></div>)}<div><dt><i />Fora de posições</dt><dd>{money(cap !== null && total(assets, "committed") !== null ? cap - total(assets, "committed")! : null, currency)}</dd></div></dl></div><small className="px-caption">Capital lógico CoinOps. Fora de posições inclui reservas de BUY; não inclui saldo externo.</small></section>
        <section className="px-panel px-limits"><h2>Limites e segurança</h2>{assets.map((item) => <div className={`px-limit px-${item.asset.toLowerCase()}`} key={item.asset}><span>{item.asset} <small>({money(item.cap ?? item.capital, currency)})</small><strong>{item.exposure !== null && (item.cap ?? item.capital) ? number(item.exposure / (item.cap ?? item.capital)! * 100, 1) + "%" : "—"}</strong></span><div className="px-meter"><i style={{ width: `${Math.min(100, item.exposure !== null && (item.cap ?? item.capital) ? item.exposure / (item.cap ?? item.capital)! * 100 : 0)}%` }} /></div></div>)}<div className="px-limit"><span>Global<strong>{number(percent, 1)}%</strong></span><div className="px-meter"><i style={{ width: `${Math.min(100, percent ?? 0)}%` }} /></div></div><ul><li>✓ {environment === "REAL" ? `Kill switch: ${health ? health.kill_switch ? "ON · protegido" : "OFF · operação autorizada" : "não verificado"}` : "Ambiente sem dinheiro real"}</li><li>✓ {environment === "REAL" ? "Somente BTCBRL e SOLBRL" : "BTC/USDC e SOL/USDC"}</li><li>✓ Saques, transferências, margem e Futures bloqueados no CoinOps</li></ul></section>
        <section className="px-panel px-activity"><div className="px-section-heading"><h2>Últimas atividades</h2><button type="button" className="px-button" onClick={() => setPanel("audit")}>Ver todas ›</button></div>{events.slice(0, 5).map((event, index) => <div className="px-event" key={`${event.id}-${index}`}><time>{time(event.at).split(", ")[1] ?? time(event.at)}</time><span>{event.type.replaceAll("_", " ")}<small>{event.asset}{event.slotNumber ? ` · Slot #${event.slotNumber}` : ""}</small></span><b>Ledger</b></div>)}{!events.length ? <p className="px-empty">Sem eventos recentes disponíveis.</p> : null}</section></div>
      <section className="px-panel px-system"><h2>Status do sistema</h2><div>{[
        ["server", "Executor", health?.healthy ? "ONLINE" : "VERIFICAR", data.livePreparation?.executor.ip ?? "Não consultado"],
        ["shield", "Binance API", health?.binance_connectivity === "OK" ? "CONECTADA" : "VERIFICAR", health ? `${health.latency_ms} ms · GET` : "Sem evidência"],
        ["server", "Banco de dados", "LEDGER LIDO", "Supabase · coinops"],
        ["chart", "Strategy Engine", healthy ? "ATIVA" : "VERIFICAR", `${assets.map((item) => item.slots.length).join(" / ")} slots físicos`],
        ["shield", "Reconciliação", healthy ? "SEM ERRO ATIVO" : "ATENÇÃO", time(checked)],
        ["reports", "Versão publicada", data.deploymentSha?.slice(0, 7) ?? "LOCAL", "Interface 5.5 · monitor server-side 6h"],
      ].map(([icon, label, value, detail]) => <div key={label}><PremiumIcon name={icon as IconName} /><span><small>{label}</small><strong>{value}</strong><small>{detail}</small></span></div>)}</div></section>
      {marketTicker}
      <footer className="px-footer"><span><strong>CoinOps</strong> · Operando com disciplina. Sempre.</span><span><i />{environment === "REAL" ? liveActive ? "LIVE PRODUCTION" : "PRODUCTION · PREPARAÇÃO" : environment === "SHADOW" ? "SHADOW VIRTUAL" : "BINANCE TESTNET"}</span><span>Dados consultados · {time(checked)}</span></footer>
    </main>
    <nav className="px-bottom-nav" aria-label="Navegação principal"><a href="/dashboard"><PremiumIcon name="home" />Resumo</a><button type="button" onClick={goOperations}><PremiumIcon name="orders" />Operações</button><a href={`/automacao?view=${view}`} aria-current="page"><span className="px-bot"><PremiumIcon name="server" /></span>Automação</a><a href="/relatorios"><PremiumIcon name="reports" />Relatórios</a><button type="button" onClick={() => setPanel("menu")}><PremiumIcon name="menu" />Mais</button></nav>
    <PremiumDrawer open={panel !== null} title={title} onClose={() => setPanel(null)}>
      <div hidden={panel !== "strategy"}>{view === "overview" ? <p>Selecione <a href="/automacao?view=live">Real</a>, <a href="/automacao?view=shadow">Shadow</a> ou <a href="/automacao?view=testnet">Testnet</a> para configurar o perfil isolado.</p> : strategyPanel}</div>
      {/* Keep the one adjustment form mounted: previews and idempotency keys must survive closing the drawer. */}
      <div hidden={panel !== "adjustments"}>{adjustmentsPanel}</div>
      {panel === "simulator" ? <div className="px-simulator-links"><a href="/automacao/simulador-ath"><PremiumIcon name="strategy" /><strong>Simulador ATH</strong><p>Regime, Top 15 / Reserve, floor e prioridade de reentrada.</p><span>Explorar cenários →</span></a><a href="/automacao/simulador-ajustes"><PremiumIcon name="adjust" /><strong>Simulador de ajustes A–J</strong><p>Provas contábeis de gains, aportes e posições abertas.</p><span>Ver cenários determinísticos →</span></a><p>Simulações isoladas. Não criam ordens nem movimentam saldo.</p></div> : null}
      {panel === "config" || panel === "audit" ? <><div className="px-asset-switch">{(["BTC", "SOL"] as const).map((item) => <button type="button" key={item} aria-pressed={asset === item} onClick={() => setAsset(item)}><AssetIcon asset={item} />{item}</button>)}</div>{panel === "config" ? <PremiumControls key={asset} data={data} view={view} asset={asset} /> : <AutomationDetails key={asset} view={view === "overview" ? "live" : view} data={data} section="all" asset={asset} />}</> : null}
      {panel === "asset" ? <><div className="px-asset-switch">{(["BTC", "SOL"] as const).map((item) => <button type="button" key={item} aria-pressed={asset === item} onClick={() => setAsset(item)}><AssetIcon asset={item} />{item}</button>)}</div><SlotList key={asset} model={active} onSelect={(slot) => openSlot(slot)} /><section className="px-detail-market"><h3>Mercado {asset}/{currency} · 30 dias</h3><Trend candles={candlesFor(active)} asset={asset} symbol={`${asset}${currency}`} large /><p className="px-caption">Velas diárias públicas Binance Production. {environment === "TESTNET" ? "Referência visual; não representa os fills fictícios." : "Somente leitura."}</p></section><button type="button" className="px-button" onClick={() => setPanel("audit")}>Análise completa, histórico e detalhes técnicos →</button></> : null}
      {panel === "slot" && selectedSlot ? <><button type="button" className="px-text-button" onClick={() => setPanel("asset")}>← Voltar à lista de slots</button><div className="px-slot-detail"><span className="px-badge">{selectedSlot.label}</span><h3>{selectedSlot.nextAction}</h3><dl>{[
        ["Slot físico", `#${selectedSlot.number}${selectedSlot.physicalId ? ` · ${selectedSlot.physicalId}` : ""}`], ["Rank operacional", selectedSlot.rank], ["Grupo / rank", `${selectedSlot.group ?? "—"} / ${selectedSlot.groupRank ?? "—"}`], ["Operação", selectedSlot.operationSequence], ["Ciclo", active.cycleId], ["Saldo composto", money(selectedSlot.balance, currency)], ["Capital em posição", money(selectedSlot.committed, currency)], ["Quantidade", `${number(selectedSlot.quantity, 8)} ${asset}`], ["Entrada", money(selectedSlot.entryPrice, currency)], ["Preço atual", money(selectedSlot.currentPrice, currency)], ["TP", money(selectedSlot.tpPrice, currency)], ["Gains totais", selectedSlot.gains], ["Gains mês / meta", `${selectedSlot.monthlyGains ?? "?"}/${selectedSlot.goal}`], ["Elegibilidade", selectedSlot.targetReached ? "META BATIDA" : selectedSlot.eligible === null ? "Sem evidência" : selectedSlot.eligible ? "Elegível" : "Não elegível"], ["P&L realizado", money(selectedSlot.realizedPnl, currency)], ["P&L aberto", money(selectedSlot.openPnl, currency)], ["Taxas", money(selectedSlot.fees, currency)],
      ].map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{value ?? "—"}</dd></div>)}</dl><h3>Ordens e ownership</h3>{selectedSlot.orders.map((order) => <div className="px-order-detail" key={order.id}><strong>{order.side} · {order.purpose} · {order.status}</strong><p>{money(order.price, currency)} · {number(order.quantity, 8)} {asset}</p><small>clientOrderId</small><code>{order.id}</code><small>Binance orderId</small><code>{order.exchangeId ?? "Sem ID de exchange"}</code></div>)}<h3>Eventos deste slot</h3>{selectedSlot.events.map((event, index) => <details key={`${event.id}-${index}`}><summary>{time(event.at)} · {event.type}</summary><pre>{JSON.stringify(event.details, null, 2)}</pre></details>)}<details><summary>Evidência completa · saldo, fees e ajustes</summary><pre>{JSON.stringify(selectedSlot.raw, null, 2)}</pre></details>{environment !== "REAL" ? <a className="px-button" href={`/automacao?view=${view}&adjust=${environment}:${asset}:${selectedSlot.number}`}>Adicionar gain ou aporte</a> : null}<a className="px-button" href="/relatorios">Histórico e auditoria completa →</a></div></> : null}
      {panel === "menu" ? <nav className="px-menu-links">{[["/dashboard", "Resumo"], ["/slots", "Slots manuais"], ["/plano-crescimento", "Plano"], ["/historico", "Histórico"], ["/relatorios", "Relatórios"], ["/mais", "Mais e configurações"]].map(([href, label]) => <a key={href} href={href}>{label}<PremiumIcon name="arrow" /></a>)}<p>{userLabel}</p></nav> : null}
    </PremiumDrawer>
  </div>;
}
