export type ReportSlotRow={asset:string;slot_number:number;status:string;target:number;cycle_real_gains:number;cycle_redistribution_in:number;cycle_redistribution_out:number;cycle_external_gain_equivalent:number;cycle_progress:number;operational_value_start:number;operational_value_end?:number|null;entries_count:number;gains_count:number};
const csvCell=(value:unknown)=>{const text=String(value??"");return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text};
export function buildCycleCsv(rows:ReportSlotRow[]){const headers=["asset","slot","status","target","real_gains","redistribution_in","redistribution_out","external_equivalent","progress","initial_value","final_value","entries","gains"];return[headers.join(","),...rows.map((row)=>[row.asset,row.slot_number,row.status,row.target,row.cycle_real_gains,row.cycle_redistribution_in,row.cycle_redistribution_out,row.cycle_external_gain_equivalent,row.cycle_progress,row.operational_value_start,row.operational_value_end??"",row.entries_count,row.gains_count].map(csvCell).join(","))].join("\n")}

const PAGE_WIDTH=595,PAGE_HEIGHT=842,MARGIN_X=48,CONTENT_TOP=770,CONTENT_BOTTOM=58,LINE_HEIGHT=14,MAX_LINE_LENGTH=108;
const LINES_PER_PAGE=Math.floor((CONTENT_TOP-CONTENT_BOTTOM)/LINE_HEIGHT);
const pdfEscape=(value:string)=>value.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
const sanitizePdfText=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g,"?");
function wrapPdfLine(value:string){if(!value)return[""];const wrapped:string[]=[];let remaining=value;while(remaining.length>MAX_LINE_LENGTH){const candidate=remaining.slice(0,MAX_LINE_LENGTH+1),breakAt=candidate.lastIndexOf(" "),splitAt=breakAt>0?breakAt:MAX_LINE_LENGTH;wrapped.push(remaining.slice(0,splitAt));remaining=remaining.slice(splitAt).trimStart()}wrapped.push(remaining);return wrapped}
function paginate<T>(items:T[],pageSize:number){const pages:T[][]=[];for(let index=0;index<items.length;index+=pageSize)pages.push(items.slice(index,index+pageSize));return pages.length?pages:[[]]}
function buildPageStream(lines:string[],pageNumber:number,pageCount:number){const body=lines.flatMap((line,index)=>index?["0 -14 Td",`(${pdfEscape(line)}) Tj`]:[`(${pdfEscape(line)}) Tj`]);return["BT","/F2 10 Tf",`${MARGIN_X} 806 Td`,"(COINOPS - RELATORIO OFICIAL) Tj","ET","0.5 w",`${MARGIN_X} 796 m ${PAGE_WIDTH-MARGIN_X} 796 l S`,"BT","/F1 9 Tf",`${MARGIN_X} ${CONTENT_TOP} Td`,...body,"ET","0.5 w",`${MARGIN_X} 46 m ${PAGE_WIDTH-MARGIN_X} 46 l S`,"BT","/F1 8 Tf",`${MARGIN_X} 30 Td`,`(Pagina ${pageNumber} de ${pageCount}) Tj`,"ET"].join("\n")}
export function buildSimplePdf(lines:string[]){const safeLines=lines.flatMap((line)=>wrapPdfLine(sanitizePdfText(line))).filter((line,index)=>index!==0||line!=="COINOPS - RELATORIO OFICIAL"),pages=paginate(safeLines,LINES_PER_PAGE),pageCount=pages.length,firstPageId=3,firstStreamId=firstPageId+pageCount,regularFontId=firstStreamId+pageCount,boldFontId=regularFontId+1,pageIds=pages.map((_,index)=>firstPageId+index),objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pageIds.map((id)=>`${id} 0 R`).join(" ")}] /Count ${pageCount} >>`];pages.forEach((_,index)=>objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${regularFontId} 0 R /F2 ${boldFontId} 0 R >> >> /Contents ${firstStreamId+index} 0 R >>`));pages.forEach((pageLines,index)=>{const stream=buildPageStream(pageLines,index+1,pageCount);objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)});objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((object,index)=>{offsets[index+1]=pdf.length;pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let index=1;index<=objects.length;index+=1)pdf+=`${String(offsets[index]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf)}

export function buildCyclePdfLines(report:{cycle_number:number;start_at:string;end_at:string|null;strategy_version:number;mode:string},rows:ReportSlotRow[]){const totalReal=rows.reduce((sum,row)=>sum+Number(row.cycle_real_gains||0),0),totalProgress=rows.reduce((sum,row)=>sum+Number(row.cycle_progress||0),0);return["COINOPS - RELATORIO OFICIAL","",`Ciclo: ${report.cycle_number}`,`Periodo: ${report.start_at} ate ${report.end_at||"em andamento"}`,`Estrategia: versao ${report.strategy_version}`,`Modo: ${report.mode}`,"Legado anterior ao baseline: excluido",`Gains reais: ${totalReal}`,`Progresso equivalente: ${totalProgress}`,"",...rows.map((row)=>`${row.asset} Slot #${row.slot_number} | ${row.cycle_progress}/${row.target} | ${row.status}`)]}
