export type FinancialOrigin = "REAL" | "ESTIMADO" | "RATEIO_ESTIMADO" | "INDISPONIVEL";
export type FinancialSourceMode = "API" | "MANUAL" | "DOCUMENTED";
export type CostCurrency = "USD" | "BRL";
export type FxQuote = { base: string; quote: "BRL"; rate: number; source: string; observedAt: string; fetchedAt: string };
export type FinopsService = {
  id: string; provider: string; name: string; shardId: string | null;
  plan: string | null; region: string | null; resourceId: string | null;
  currency: CostCurrency; recurringMonthly: number | null; actualMonthCost: number | null;
  variableMonthToDate: number | null; allocationPercent: number | null;
  costPeriod: string; origin: FinancialOrigin; sourceNote: string; sourceUrl: string | null;
  billingPeriodStart?: string | null; billingPeriodEnd?: string | null;
  sourceMode: FinancialSourceMode; pricingDate: string | null; unitPrice: number | null; quantity: number | null;
  estimatedBrl: number | null; allocatedBrl: number | null;
  syncedAt: string | null; syncStatus: "OK" | "MANUAL" | "UNAVAILABLE" | "FAILED";
  usage: Array<{ label: string; used: number | null; limit: number | null; unit: string }>;
  projectedOriginal: number | null; actualBrl: number | null; projectedBrl: number | null;
  recurringBrl: number | null; enabled: boolean;
};
export type FinopsExecutor = {
  id: string; name: string; ip: string; enabled: boolean; provider: string | null;
  region: string | null; plan: string | null; accounts: number; engines: number;
  cpuPercent: number | null; ramMb: number | null; weightCurrent: number | null;
  weightLimit: number; pressurePercent: number | null; headroomPercent: number | null;
  backlog: number | null; heartbeatAt: string | null; status: string;
  monthlyOriginal: number | null; currency: CostCurrency | null; monthlyBrl: number | null;
  costPerAccountBrl: number | null; costPerEngineBrl: number | null;
  needsCapacity: boolean; scaleRecommendation: string | null;
};
export type FinopsHistory = { period: string; capturedAt: string; accounts: number; engines: number;
  executors: number; actualBrl: number | null; projectedBrl: number | null;
  knownProjectedBrl: number; capitalBrl: number | null; costPerAccountBrl: number | null;
  costPerEngineBrl: number | null; byProvider: Record<string, number | null>;
  fx: FxQuote[]; completeness: string; closed: boolean };
export type FinopsAlert = { id: string; code: string; serviceId: string | null;
  message: string; firstSeenAt: string; lastSeenAt: string };
export type FinopsCapitalRow = { accountId: string; accountName: string; shardId: string;
  currency: string; monitored: number | null; free: number | null; reserved: number | null;
  positions: number | null; realizedPnl: number | null; openPnl: number | null;
  observedAt: string | null; source: string; complete: boolean };
export type FinopsMarketRow = { accountId: string; accountName: string; shardId: string;
  market: string; currency: string; positions: number | null; reserved: number | null;
  realizedPnl: number | null; openPnl: number | null };
export type FinopsDashboard = {
  capturedAt: string | null; period: string; syncStatus: string;
  summary: { accounts: number; engines: number; executors: number;
    capitalBrl: number | null; capitalByCurrency: Record<string, number | null>;
    actualBrl: number | null; projectedBrl: number | null; knownActualBrl: number;
    knownProjectedBrl: number; costPerAccountBrl: number | null; costPerEngineBrl: number | null;
    unavailableServices: number; capitalComplete: boolean; monthlyEstimatedBrl?: number | null;
    knownRealBrl?: number | null; estimatedBrl?: number | null; allocatedBrl?: number | null;
    costTotalsByCurrency?: Record<string, number | null> };
  capital: { accounts: FinopsCapitalRow[]; markets: FinopsMarketRow[]; notes: string[] };
  executors: FinopsExecutor[]; services: FinopsService[]; fx: FxQuote[];
  history: FinopsHistory[]; alerts: FinopsAlert[]; sources: string[];
  growth?: Array<{ additionalAccounts: number; additionalEngines: number; estimatedExecutors: number | null;
    incrementalBrl: number | null; reason: string }>;
};
export type FinopsScope = { operatorId: string; tenantId: string; userId: string };
